---
# major version of the RHEL base to use (for repos working only for rhel)
rhel_base_version: 9

# url for the latest displaylink driver (rpm package). CHECK BEFORE RUNNING !
displaylink_driver_url: https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v6.0.0/fedora-40-displaylink-1.14.4-2.github_evdi.x86_64.rpm
