---
- name: Install packages with dnf
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.fedora }}"

- name: Remove packages with dnf
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  loop: "{{ removed_packages.fedora }}"
  when: removed_packages.fedora | length > 0

- name: Enable automatic updates
  ansible.builtin.systemd_service:
    name: dnf-automatic-install.timer
    enabled: true
    state: started
