---
- block:
  - include_tasks: {{ item }}
    loop:
      - rhel_based.yml
  become: true
  when: ansible['os_family'] == "Redhat"

- block:
  - include_tasks: {{ item }}
    loop:
      - ubuntu_based.yml
  become: true
  when: ansible['os_family'] == "Debian"
