---
- name: copy zsh config file
  file:
    state: link
    path: "{{ home }}/.zshrc"
    src: "{{ conf_files.zsh }}"

- name: copy ssh config file
  file:
    state: link
    path: "{{ home }}/.ssh/config"
    src: "{{ conf_files.ssh }}"

- name: copy vim config file
  file:
    state: link
    path: "{{ nvim_config.config_file }}"
    src: "{{ conf_files.vim }}"