---

- name: create vim dir if not exists
  file:
    state: directory
    path: "{{ home }}/.local/share/nvim/site/autoload/"

- name: install vim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ nvim_config.plugin_file }}"
