---
- name: Check for repository
  stat:
    path: "{{ dotfiles.bare_location }}/HEAD"
  register: git_head
  changed_when: false

- name: Cloning bare dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.bare_location }}"
    bare: true
    clone: true
  when: not git_head.stat.exists

- name: Checking out dotfiles to $HOME and configuring git
  ansible.builtin.shell: |
    /usr/bin/git --git-dir="{{ dotfiles.bare_location }}" --work-tree=$HOME config --local status.showUntrackedFiles no
    /usr/bin/git --git-dir="{{ dotfiles.bare_location }}" --work-tree=$HOME checkout
  when: not git_head.stat.exists
