---
- name: Install docking station drivers with apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ deb_packages }}"
  when:
    - deb_packages
    - ansible_os_family == "Debian"

- name: Install docking station drivers with dnf
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  loop: "{{ rpm_packages }}"
  when:
    - rpm_packages
    - ansible_os_family == "RedHat"
