---
# xdg also creates the folders as a task, can't run everything as root
- name: Inclusion des tâches utilisateur
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - dotfiles.yml
    - tools.yml
