---
- name: Install required packages for dnf/yum modifications
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ rpm_reqs }}"

- name: Adding dnf repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    state: present
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck }}"
    sslverify: "{{ item.ssl_verify }}"
  loop: "{{ rpm_repos }}"

- name: Adding copr repositories
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop: "{{ copr_projects }}"
  when: copr_projects | length > 0
