---
git_tools:
  # tmux plugin manager
  - repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_env.HOME + '/.config') }}/tmux/tpm"

packages:
  ubuntu:
    - fd-find
    - ripgrep
    - fzf
    - exa
    - rust-bat
    - openssh-client
    - openssh-server
    - diffutils
    - neovim
    - git
    - gnupg
    - tmux
    - zsh
    - jq
    - zsh
    - zsh-autosuggestions
    - python3-pip
    - adb
    - fastboot
    - scrcpy
    - alacritty
    - xdg-user-dirs
    - speedtest-cli
    - flatpak
    - yubikey-manager
    - openjdk-11-jre
    - openjdk-17-jre
    - task
    - protonvpn
    - strongswan
    - strongswan-charon
    - strongswan-nm
    - nextcloud-desktop
    - firefox
    - keepassxc
    - gimp
    - transmission
    - mpv
    - gnome-keyring
    - seahorse
    - fwupd
  fedora:
    - fd-find
    - ripgrep
    - fzf
    - eza
    - bat
    - openssh-client
    - openssh-server
    - diffutils
    - neovim
    - git
    - gnupg2
    - tmux
    - android-tools
    - scrcpy
    - jq
    - zsh
    - zsh-autosuggestions
    - python3-pip
    - alacritty
    - speedtest-cli
    - xdg-user-dirs
    - flatpak
    - yubikey-manager
    - java-11-openjdk
    - java-17-openjdk
    - task
    - protonvpn-stable-release
    - protonvpn-cli
    - strongswan
    - strongswan-charon-nm
    - nextcloud-client
    - firefox
    - keepassxc
    - gimp
    - transmission
    - mpv
    - gnome-keyring
    - seahorse
    - nemo
    - dnf-automatic
    - fwupd
    - gnome-shell-extension-pop-shell


removed_packages:
  ubuntu: []
  fedora: []

flatpak_packages:
  - com.valvesoftware.Steam
  - org.torproject.torbrowser-launcher
  - org.signal.Signal

fonts:
  - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
