---
- name: Update apt package list
  ansible.builtin.apt:
    update-cache: true
    cache_valid_time: 14440  # évite la répétition à chaque lancement du role

- name: Install u2f packages
  ansible.builtin.apt:
    name: "{{ u2f_packages.ubuntu }}"
    state: present
