---
alternatives:
  - name: editor
    link: /usr/bin/editor
    path: /usr/bin/nvim
    priority: 10
    state: selected
  - name: vim
    link: /usr/bin/vim
    path: /usr/bin/nvim
    priority: 10
    state: selected

packages:
  debian:
    - neovim
    - git
    - tmux
    - exa
  ubuntu:
    - neovim
    - git
    - tmux
    - exa
