---
- name: Vérification de la présence du dépôt dotfiles
  ansible.builtin.stat:
    path: "{{ dotfiles.bare_location }}/HEAD"
  register: git_head
  changed_when: false

- name: Clonage du dépôt dotfiles en bare
  ansible.builtin.git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.bare_location }}"
    bare: true
    clone: true
  when: not git_head.stat.exists

- name: Extraction des dotfiles dans le home et configuration de git
  ansible.builtin.shell: |
    /usr/bin/git --git-dir={{ dotfiles.bare_location }} --work-tree={{ dotfiles.work_tree }} config --local status.showUntrackedFiles no
    /usr/bin/git --git-dir={{ dotfiles.bare_location }} --work-tree={{ dotfiles.work_tree }} checkout
  when: not git_head.stat.exists
  changed_when: true
