---
git_tools:
  - repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME + '/.config') }}/tmux/plugins/tpm/"
    delete_git_folder: true
  - repo: https://github.com/LazyVim/starter
    dest: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME + '/.config') }}/nvim"
    delete_git_folder: true

uv_tools:
  - name: install-release
  # ansible is not necessary on a server
  # - name: ansible
  #   with_executables_from:
  #     - ansible-core
  #   with:
  #     - pywinrm
  #     - dnspython
  #     # - kerberos
