---
dotfiles:
  repo: https://github.com/SalutAToi/dotfiles.git
  bare_location: $XDG_CONFIG_HOME/dotfiles
  work_tree: $HOME

git_tools:
  - repo: https://github.com/tmux-plugins/tpm
    dest: $XDG_CONFIG_HOME/tmux/tpm
