---
# using $HOME instead of XDG variables as profile.d vars are not evaluated by ansible
dotfiles:
  repo: https://github.com/SalutAToi/dotfiles.git
  bare_location: $HOME/.config/dotfiles
  work_tree: $HOME

git_tools:
  - repo: https://github.com/tmux-plugins/tpm
    dest: $HOME/.config/tmux/plugins/tpm/
