---
- name: Mise à jour de la liste des paquets apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 14440

- name: Installation des paquets TPM
  ansible.builtin.apt:
    name: "{{ tpm_packages.ubuntu }}"
    state: present
