---
- name: Install packages for Ubuntu based
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.ubuntu }}"
  when: ansible_distribution == "Pop!_OS" or ansible_distribution == "Ubuntu"

- name: Install packages for Fedora
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.fedora }}"
  when: ansible_distribution == "Fedora"

- name: Installation système de uv
  ansible.builtin.shell:
    cmd: "set -o pipefail && curl -LsSf {{ uv_install_script_url }} | sh"
    executable: /bin/bash
    creates: "{{ uv_install_dir }}/uv"
  environment:
    UV_INSTALL_DIR: "{{ uv_install_dir }}"
    UV_NO_MODIFY_PATH: "1"
